/**
 * Representative Agentic AI Natural Language Cypher Queries
 * Used for GraphRAG validation and connectivity checks.
 */

module.exports = [
  { id: 1, category: "Performance", text: "Who are the top 10 students in CSE?", cypher: `MATCH (d:Department {code:"CSE"})<-[:BELONGS_TO]-(s:Student)-[:HAS_RESULT]->(r:Result) WHERE r.marks <> -1 RETURN s.studentId AS student, sum(r.marks) AS total ORDER BY total DESC LIMIT 10` },
  { id: 2, category: "Performance", text: "Who are the top 10 students in batch 2023-2027?", cypher: `MATCH (b:Batch {batchName:"2023-2027"})<-[:BELONGS_TO]-(s:Student)-[:HAS_RESULT]->(r:Result) WHERE r.marks <> -1 RETURN s.studentId AS student, sum(r.marks) AS total ORDER BY total DESC LIMIT 10` },
  { id: 3, category: "Subject", text: "Which subjects have the lowest average?", cypher: `MATCH (sub:Subject)<-[:FOR_SUBJECT]-(r:Result) WHERE r.marks <> -1 RETURN sub.name AS subject, avg(r.marks) AS avgMarks ORDER BY avgMarks ASC` },
  { id: 4, category: "Faculty", text: "Which faculty teach those subjects?", cypher: `MATCH (sub:Subject)<-[:TEACHES]-(f:Faculty)-[:HAS_PROFILE]-(u:User) RETURN sub.name AS subject, u.fullName AS faculty` },
  { id: 5, category: "Performance", text: "Which students are weak in AI?", cypher: `MATCH (sub:Subject {name:"Artificial Intelligence"})<-[:FOR_SUBJECT]-(r:Result)<-[:HAS_RESULT]-(s:Student)-[:HAS_PROFILE]-(u:User) WHERE r.marks < 50 AND r.marks <> -1 RETURN u.fullName AS student` },
  { id: 6, category: "Examination", text: "Which students have unavailable Internal 2 marks?", cypher: `MATCH (s:Student)-[:HAS_RESULT]->(r:Result {marks:-1})-[:FOR_EXAM]->(e:Examination {examSessionId:"exs2"}), (u:User)-[:HAS_PROFILE]->(s) RETURN u.fullName AS student` },
  { id: 7, category: "Timetable", text: "What classes does Student1 have tomorrow?", cypher: `MATCH (s:Student {studentId:"stu1"})-[:BELONGS_TO]->(b:Batch)<-[:FOR_BATCH]-(te:TimetableEntry {dayOfWeek:"TUESDAY"}), (te)-[:FOR_SUBJECT]->(sub:Subject) RETURN te.periodNumber AS period, sub.name AS subject` },
  { id: 8, category: "Timetable", text: "Which room does Student1 go to for period 1?", cypher: `MATCH (s:Student {studentId:"stu1"})-[:BELONGS_TO]->(b:Batch)<-[:FOR_BATCH]-(te:TimetableEntry {dayOfWeek:"MONDAY", periodNumber:1}), (te)-[:HELD_IN]->(r:Room) RETURN r.roomNumber AS room` },
  { id: 9, category: "Timetable", text: "Who teaches the subject Student1 has tomorrow?", cypher: `MATCH (s:Student {studentId:"stu1"})-[:BELONGS_TO]->(b:Batch)<-[:FOR_BATCH]-(te:TimetableEntry {dayOfWeek:"TUESDAY"}), (te)-[:TAUGHT_BY]->(f:Faculty)-[:HAS_PROFILE]-(u:User) RETURN DISTINCT u.fullName AS faculty` },
  { id: 10, category: "Faculty", text: "Which students are taught by Faculty1?", cypher: `MATCH (f:Faculty {facultyId:"fac1"})-[:TEACHES]->(sub:Subject)<-[:HAS_SUBJECT]-(sem:AcademicSemester)<-[:CURRENTLY_IN]-(s:Student), (u:User)-[:HAS_PROFILE]->(s) RETURN DISTINCT u.fullName AS student` },
  { id: 11, category: "Faculty", text: "Which students performed poorly in subjects taught by Faculty1?", cypher: `MATCH (f:Faculty {facultyId:"fac1"})-[:TEACHES]->(sub:Subject)<-[:FOR_SUBJECT]-(r:Result)<-[:HAS_RESULT]-(s:Student), (u:User)-[:HAS_PROFILE]->(s) WHERE r.marks < 50 AND r.marks <> -1 RETURN DISTINCT u.fullName AS student` },
  { id: 12, category: "Batch", text: "Compare batch 2023-2027 and 2024-2028 average CGPA.", cypher: `MATCH (b:Batch)<-[:BELONGS_TO]-(s:Student) RETURN b.batchName AS batch, avg(s.currentCGPA) AS avgCGPA` },
  { id: 13, category: "Department", text: "Which department has the highest average performance?", cypher: `MATCH (d:Department)<-[:BELONGS_TO]-(s:Student)-[:HAS_RESULT]->(r:Result) WHERE r.marks <> -1 RETURN d.name AS dept, avg(r.marks) AS avgMarks ORDER BY avgMarks DESC` },
  { id: 14, category: "Subject", text: "Which subject has the highest failure rate?", cypher: `MATCH (sub:Subject)<-[:FOR_SUBJECT]-(r:Result {status:"FAIL"}) RETURN sub.name AS subject, count(r) AS failCount ORDER BY failCount DESC` },
  { id: 15, category: "Faculty", text: "Which faculty are teaching that subject?", cypher: `MATCH (sub:Subject)<-[:TEACHES]-(f:Faculty)-[:HAS_PROFILE]-(u:User) RETURN sub.name AS subject, u.fullName AS faculty` },
  { id: 16, category: "Assessment", text: "Which students have assessments pending?", cypher: `MATCH (subm:Submission {status:"PENDING"})<-[:SUBMITTED]-(s:Student), (u:User)-[:HAS_PROFILE]->(s) RETURN u.fullName AS student` },
  { id: 17, category: "Assessment", text: "Which topics are associated with weak-performing students?", cypher: `MATCH (s:Student)-[:HAS_RESULT]->(r:Result {status:"FAIL"})-[:FOR_SUBJECT]->(sub:Subject)<-[:FOR_SUBJECT]-(a:Assessment)-[:CONTAINS]->(q:Question)-[:TESTS]->(top:Topic) RETURN DISTINCT top.name AS topic` },

  // Derived Connectivity
  { id: 51, category: "Derived Connectivity", text: "Which subjects does Student1 study?", cypher: `MATCH (s:Student {studentId:"stu1"})-[:STUDIES]->(sub:Subject) RETURN sub.subjectCode AS code, sub.name AS subject` },
  { id: 52, category: "Derived Connectivity", text: "Which students study Artificial Intelligence?", cypher: `MATCH (s:Student)-[:STUDIES]->(sub:Subject {name:"Artificial Intelligence"}), (u:User)-[:HAS_PROFILE]->(s) RETURN u.fullName AS student` },
  { id: 53, category: "Derived Connectivity", text: "Which subjects are studied by students in batch 2023-2027?", cypher: `MATCH (b:Batch {batchName:"2023-2027"})<-[:BELONGS_TO]-(s:Student)-[:STUDIES]->(sub:Subject) RETURN DISTINCT sub.name AS subject` },
  { id: 54, category: "Derived Connectivity", text: "Which examinations belong to Semester 7?", cypher: `MATCH (e:Examination)-[:FOR_SEMESTER]->(sem:AcademicSemester {name:"Semester 7"}) RETURN e.examId AS examId, e.examName AS name` },
  { id: 55, category: "Derived Connectivity", text: "Which examination session contains examinations for Semester 7?", cypher: `MATCH (sem:AcademicSemester {name:"Semester 7"})<-[:FOR_SEMESTER]-(e:Examination)<-[:HAS_EXAM]-(es:ExaminationSession) RETURN DISTINCT es.name AS session` },
  { id: 56, category: "Derived Connectivity", text: "Which students wrote examinations in this examination session?", cypher: `MATCH (es:ExaminationSession {examSessionId:"exs1"})-[:HAS_EXAM]->(e:Examination)<-[:FOR_EXAM]-(r:Result)<-[:HAS_RESULT]-(s:Student), (u:User)-[:HAS_PROFILE]->(s) RETURN DISTINCT u.fullName AS student` },

  // ClassSection Queries (20 Queries)
  { id: 67, category: "ClassSection", text: "Who is the advisor for CSE 2023-2027 Section A?", cypher: `MATCH (cs:ClassSection {sectionId:"sec1"})-[:HAS_ADVISOR]->(f:Faculty), (u:User)-[:HAS_PROFILE]->(f) RETURN u.fullName AS advisor` },
  { id: 68, category: "ClassSection", text: "Who are the students in Section A?", cypher: `MATCH (s:Student)-[:MEMBER_OF]->(cs:ClassSection {sectionId:"sec1"}), (u:User)-[:HAS_PROFILE]->(s) RETURN u.fullName AS student` },
  { id: 69, category: "ClassSection", text: "Which batch does Section A belong to?", cypher: `MATCH (b:Batch)-[:HAS_SECTION]->(cs:ClassSection {sectionId:"sec1"}) RETURN b.batchName AS batch` },
  { id: 70, category: "ClassSection", text: "Which course does Section A belong to?", cypher: `MATCH (c:Course)<-[:FOR_COURSE]-(b:Batch)-[:HAS_SECTION]->(cs:ClassSection {sectionId:"sec1"}) RETURN c.courseName AS course` },
  { id: 71, category: "ClassSection", text: "Which department does Section A belong to?", cypher: `MATCH (d:Department)<-[:ASSOCIATED_WITH]-(b:Batch)-[:HAS_SECTION]->(cs:ClassSection {sectionId:"sec1"}) RETURN d.name AS dept` },
  { id: 72, category: "ClassSection", text: "What is Section A's timetable?", cypher: `MATCH (te:TimetableEntry)-[:FOR_SECTION]->(cs:ClassSection {sectionId:"sec1"}), (te)-[:FOR_SUBJECT]->(sub:Subject), (te)-[:TAUGHT_BY]->(f:Faculty), (u:User)-[:HAS_PROFILE]->(f) RETURN te.dayOfWeek AS day, te.periodNumber AS period, sub.name AS subject, u.fullName AS faculty ORDER BY te.dayOfWeek, te.periodNumber` },
  { id: 73, category: "ClassSection", text: "Which faculty teach Section A?", cypher: `MATCH (te:TimetableEntry)-[:FOR_SECTION]->(cs:ClassSection {sectionId:"sec1"}), (te)-[:TAUGHT_BY]->(f:Faculty), (u:User)-[:HAS_PROFILE]->(f) RETURN DISTINCT u.fullName AS faculty` },
  { id: 74, category: "ClassSection", text: "Which rooms does Section A use?", cypher: `MATCH (te:TimetableEntry)-[:FOR_SECTION]->(cs:ClassSection {sectionId:"sec1"}), (te)-[:HELD_IN]->(r:Room) RETURN DISTINCT r.roomNumber AS room, r.building AS building` },
  { id: 75, category: "ClassSection", text: "What subjects does Section A have?", cypher: `MATCH (te:TimetableEntry)-[:FOR_SECTION]->(cs:ClassSection {sectionId:"sec1"}), (te)-[:FOR_SUBJECT]->(sub:Subject) RETURN DISTINCT sub.subjectCode AS code, sub.name AS name` },
  { id: 76, category: "ClassSection", text: "Which students are taught by Faculty1?", cypher: `MATCH (f:Faculty {facultyId:"fac1"})<-[:TAUGHT_BY]-(te:TimetableEntry)-[:FOR_SECTION]->(cs:ClassSection)<-[:MEMBER_OF]-(s:Student), (u:User)-[:HAS_PROFILE]->(s) RETURN DISTINCT u.fullName AS student` },
  { id: 77, category: "ClassSection", text: "Which students are under Faculty1 as advisor?", cypher: `MATCH (f:Faculty {facultyId:"fac1"})<-[:HAS_ADVISOR]-(cs:ClassSection)<-[:MEMBER_OF]-(s:Student), (u:User)-[:HAS_PROFILE]->(s) RETURN u.fullName AS student` },
  { id: 78, category: "ClassSection", text: "Which classes does Faculty1's advisory section have today?", cypher: `MATCH (f:Faculty {facultyId:"fac1"})<-[:HAS_ADVISOR]-(cs:ClassSection)<-[:FOR_SECTION]-(te:TimetableEntry {dayOfWeek:"MONDAY"}), (te)-[:FOR_SUBJECT]->(sub:Subject) RETURN te.periodNumber AS period, sub.name AS subject` },
  { id: 79, category: "ClassSection", text: "Which students in Section A scored below 60?", cypher: `MATCH (cs:ClassSection {sectionId:"sec1"})<-[:MEMBER_OF]-(s:Student)-[:HAS_RESULT]->(r:Result), (u:User)-[:HAS_PROFILE]->(s) WHERE r.marks < 60 AND r.marks <> -1 RETURN DISTINCT u.fullName AS student, r.marks AS marks` },
  { id: 80, category: "ClassSection", text: "Which students in Section A are weak in Topic X?", cypher: `MATCH (cs:ClassSection {sectionId:"sec1"})<-[:MEMBER_OF]-(s:Student)-[:WEAK_IN]->(top:Topic), (u:User)-[:HAS_PROFILE]->(s) RETURN u.fullName AS student, top.name AS topic` },
  { id: 81, category: "ClassSection", text: "Compare Section A and Section B average marks.", cypher: `MATCH (cs:ClassSection)<-[:MEMBER_OF]-(s:Student)-[:HAS_RESULT]->(r:Result) WHERE r.marks <> -1 RETURN cs.sectionName AS section, avg(r.marks) AS avgMarks` },
  { id: 82, category: "ClassSection", text: "Which section has the highest average marks?", cypher: `MATCH (cs:ClassSection)<-[:MEMBER_OF]-(s:Student)-[:HAS_RESULT]->(r:Result) WHERE r.marks <> -1 RETURN cs.displayName AS section, avg(r.marks) AS avgMarks ORDER BY avgMarks DESC LIMIT 1` },
  { id: 83, category: "ClassSection", text: "Which section has the most students?", cypher: `MATCH (cs:ClassSection)<-[:MEMBER_OF]-(s:Student) RETURN cs.displayName AS section, count(s) AS stdCount ORDER BY stdCount DESC LIMIT 1` },
  { id: 84, category: "ClassSection", text: "Which faculty teaches the most classes in Section A?", cypher: `MATCH (te:TimetableEntry)-[:FOR_SECTION]->(cs:ClassSection {sectionId:"sec1"}), (te)-[:TAUGHT_BY]->(f:Faculty), (u:User)-[:HAS_PROFILE]->(f) RETURN u.fullName AS faculty, count(te) AS classCount ORDER BY classCount DESC LIMIT 1` },
  { id: 85, category: "ClassSection", text: "What exam is Section A preparing for?", cypher: `MATCH (cs:ClassSection {sectionId:"sec1"})<-[:HAS_SECTION]-(b:Batch)-[:HAS_EXAMINATION_SESSION]->(es:ExaminationSession) RETURN es.name AS examSession` },
  { id: 86, category: "ClassSection", text: "Which students in Section A have missing marks?", cypher: `MATCH (cs:ClassSection {sectionId:"sec1"})<-[:MEMBER_OF]-(s:Student)-[:HAS_RESULT]->(r:Result {marks:-1}), (u:User)-[:HAS_PROFILE]->(s) RETURN DISTINCT u.fullName AS student` }
];
